version: "3.8"

services:
  mathgame-backend:
    build:
      context: ./mathgame
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DEFAULTCONNECTION}
    restart: unless-stopped
    networks:
      - mathgame-net
    depends_on:
      mathgame-postgres:
        condition: service_healthy

  mathgame-postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT_MACHINE_POSTGRES}:5432"
    restart: unless-stopped
    networks:
      - mathgame-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  mathgame-net:
    external: true